### ISSUE TITLE
can I force installation on a R 3.5 from github?

### ISSUE THREAD

**Issue by agranado** [SydneyBioX/scMerge#22]
Hi, 
I was wondering whether the requirement of v3.6 is essential and why? Thank you
Just asking bc updating R can be a pain...

**Comment by kevinwang09** [comment]
Hi,
You can follow the instructions here: https://github.com/SydneyBioX/scMerge/issues/11#issuecomment-539279364

The reason for R version 3.6 or higher is because `scMerge` is part of the Bioconductor software, which has a very strict requirement that all packages must be developed with respect to the latest release of R and other dependent Bioconductor packages. When R moved from 3.5 and 3.6, there were some major changes to R and dependent packages. Hence, whenever possible, I would strongly recommend updating R and Bioconductor to their latest versions. 

Thanks, 
Kevin

**Comment by agranado** [comment]
Ahh great. Thanks, I think updating to 3.6 is probably what makes the most sense. 

Alejandro
